language: node_js

node_js:
  - 'node'
  - '7'
  - '6'

install:
  - npm install
  - npm prune

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - 'node_modules'

notifications:
  email:
    on_success: never
    on_failure: always
